"""schema inicial

Migration unica. As quatro anteriores (0001..0004) foram esmagadas nesta: sem
banco em producao, manter a cadeia historica so preservava as decisoes que ja
haviam sido revertidas — inclusive a decomposicao da persona legada e o
sentinela max_tokens=0, ambos sem proposito agora.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('personality', sa.Text(), server_default='', nullable=False),
    sa.Column('humor', sa.Text(), server_default='', nullable=False),
    sa.Column('tone', sa.Text(), server_default='', nullable=False),
    sa.Column('energy', sa.Text(), server_default='', nullable=False),
    sa.Column('objective', sa.Text(), server_default='', nullable=False),
    sa.Column('avoid', sa.Text(), server_default='', nullable=False),
    sa.Column('extra_instructions', sa.Text(), server_default='', nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('avatar_emoji', sa.String(length=24), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_is_archived'), ['is_archived'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_kind'), ['kind'], unique=False)

    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('model_id', sa.String(length=240), nullable=False),
    sa.Column('temperature_milli', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_p_milli', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_provider_model')
    )
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_configs_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_configs_provider_id'), ['provider_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('model_config_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_model_config_id'), ['model_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_persona_id'), ['persona_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='global', nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope in ('global', 'persona', 'conversation')", name='ck_memories_scope'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_persona_id'), ['persona_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_scope'), ['scope'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='complete', nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=240), nullable=True),
    sa.Column('provider_kind', sa.String(length=40), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name='ck_messages_role'),
    sa.CheckConstraint("status in ('complete', 'failed', 'cancelled')", name='ck_messages_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_scope'))
        batch_op.drop_index(batch_op.f('ix_memories_persona_id'))
        batch_op.drop_index(batch_op.f('ix_memories_is_active'))
        batch_op.drop_index(batch_op.f('ix_memories_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_memories_category'))

    op.drop_table('memories')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_persona_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_model_config_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_is_archived'))

    op.drop_table('conversations')
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_configs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_model_configs_is_archived'))

    op.drop_table('model_configs')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_kind'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_is_archived'))

    op.drop_table('personas')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
